"""Stable public API for ARCH Web W01 contracts."""

from arch_web.__about__ import __version__
from arch_web.contracts import (
    CURRENT_WEB_CONTRACT_VERSION,
    SUPPORTED_WEB_CONTRACT_VERSIONS,
    canonical_bytes,
    contract_fingerprint,
    decode_contract,
    encode_contract,
)
from arch_web.domain import (
    ArchitectureChoice,
    ContractRef,
    DesignReference,
    EvidenceRef,
    ProjectKind,
    RequirementCategory,
    RequirementPriority,
    RequirementStatus,
    RouteVisibility,
    SurfaceType,
    UnsupportedWebContractVersionError,
    WebContractError,
    WebContractIntegrityError,
    WebContractReferenceError,
    WebContractValidationError,
    WebInformationArchitectureContract,
    WebLifecycleStatus,
    WebProjectProfile,
    WebRequirement,
    WebRequirementsContract,
    WebRoute,
    WebRouteContract,
    WebStackProfile,
    WebSurface,
)

__all__ = (
    "CURRENT_WEB_CONTRACT_VERSION",
    "SUPPORTED_WEB_CONTRACT_VERSIONS",
    "ArchitectureChoice",
    "ContractRef",
    "DesignReference",
    "EvidenceRef",
    "ProjectKind",
    "RequirementCategory",
    "RequirementPriority",
    "RequirementStatus",
    "RouteVisibility",
    "SurfaceType",
    "UnsupportedWebContractVersionError",
    "WebContractError",
    "WebContractIntegrityError",
    "WebContractReferenceError",
    "WebContractValidationError",
    "WebInformationArchitectureContract",
    "WebLifecycleStatus",
    "WebProjectProfile",
    "WebRequirement",
    "WebRequirementsContract",
    "WebRoute",
    "WebRouteContract",
    "WebStackProfile",
    "WebSurface",
    "__version__",
    "canonical_bytes",
    "contract_fingerprint",
    "decode_contract",
    "encode_contract",
)
