"""Narrow ports for external W05 effects."""

from __future__ import annotations

from collections.abc import Iterable
from contextlib import AbstractContextManager
from pathlib import Path
from typing import Protocol

from arch_web.domain.workspace import RepositoryBaseline, WorkspaceBaseline, WorkspaceTarget


class FileSystemPort(Protocol):
    def inspect(
        self, target: WorkspaceTarget, repository: RepositoryBaseline
    ) -> WorkspaceBaseline: ...
    def exists(self, path: str) -> bool: ...
    def read_bytes(self, path: str) -> bytes: ...
    def create_directory(self, path: str) -> None: ...
    def write_bytes(self, path: str, content: bytes) -> None: ...
    def delete_file(self, path: str) -> None: ...
    def remove_directory(self, path: str) -> None: ...


class VersionControlPort(Protocol):
    def inspect(self) -> RepositoryBaseline: ...
    def initialize(self) -> None: ...
    def commit(self, paths: Iterable[str], message: str) -> str: ...


class WorkspaceLockPort(Protocol):
    def acquire(self, root: Path, execution_id: str) -> AbstractContextManager[None]: ...


__all__ = ("FileSystemPort", "VersionControlPort", "WorkspaceLockPort")
